[tool.poetry]
name = "p3"
version = "0.1.0"
description = "Potential talents"
authors = ["srkpa <kpanou.rogia@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
